version: '3.5'

services:
  database:
    container_name: database
    image: postgres:14.7-alpine
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - database
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.net
      - PGADMIN_DEFAULT_PASSWORD=54321!
    ports:
      - "5400:80"

volumes:
  database:
